spring.application.name=BankManagementSystemProject
spring.datasource.url=jdbc:mysql://localhost:3306/SpringBootBMS

spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

# Login
spring.security.user.name=hitesh
spring.security.user.password=12345